### ISSUE TITLE
Use NLTK tokenizer

### ISSUE THREAD

**Issue by orbisvicis** [alvations/pywsd#2]
Replace `"".split()` with `nltk.word_tokenizer()`

**Comment by alvations** [comment]
`pywsd.disambiguate()` function uses `nltk.word_tokenize()` and `nltk.pos_tag()` by default. 

`pywsd.utils.lemmatize` and `pywsd.utils.lemmatize_sentence` allows for  custom tokenizer and postagger that gives the same output type as nltk's.
