### ISSUE TITLE
Error running test_wsd.py after installation

### ISSUE THREAD

**Issue by SohaKh** [alvations/pywsd#23]
I'm trying to start using wsdpy, but with running test_wsd.py or any simple example I get error like "in File lesk.py line 116, in simple_signature
    signature+= list(chain(*[i.lemma_names() for i in ss_hypohypernyms]))
TypeError: 'list' object is not callable" and other errors. I don't know whether I missed something or it is a bug.

**Comment by alvations** [comment]
This is strange. I've just tested from scratch and it has no problem (http://pastebin.com/raw.php?i=uVFHG6Dw)

Have you installed `nltk`?

**Comment by SohaKh** [comment]
yes

**Comment by SohaKh** [comment]
I'm on fedora linux. I did yum search nltk, I didn't find it. so I
installed python-nltk.

**Comment by SohaKh** [comment]
maybe I need to install other libraries. (any idea?)

**Comment by alvations** [comment]
Which python version are you using?

**Comment by SohaKh** [comment]
Python 2.7.5

**Comment by alvations** [comment]
can you do this:

```
python -c "import nltk; nltk.download('wordnet')"
```

and then re-run

```
python test_wsd.py
```

**Comment by SohaKh** [comment]
I did. I got same result.

**Comment by alvations** [comment]
Did you get these output from checking the nltk version and wordnet?

```
alvas@ubi:~/test/pywsd$ python -c "import nltk; print nltk.__version__"
3.0.3
alvas@ubi:~/test/pywsd$ python -c "import nltk; nltk.download('wordnet')"
[nltk_data] Downloading package wordnet to /home/alvas/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
```

**Comment by SohaKh** [comment]
version of my nltk is 2.04.
I installed it couple of hours ago. I don't know why it is old.

**Comment by SohaKh** [comment]
How can I install a new version?

**Comment by alvations** [comment]
I think the yum package in NLTK is stale. Use `pip` install as suggested on http://www.nltk.org/install.html . Can you use `pip install` to install NLTK instead?

First, install http://www.liquidweb.com/kb/how-to-install-pip-on-fedora-21/

```
yum clean all
yum -y update
yum -y install python-pip
```

Then install `nltk` and `numpy` using pip:

```
sudo pip install -U nltk
sudo pip install -U numpy
```

Then

```
python -c "import nltk; print nltk.__version__"
python -c "import nltk; nltk.download('wordnet')"
```

And finally

```
python test_wsd.py
```

**Comment by SohaKh** [comment]
Thank you so much for providing the pywsd publicly, and for your immediate
help.
Now it's working.

Thanks again,
Soha

**Comment by alvations** [comment]
No problem =)
Have fun with the library!

**Comment by SohaKh** [comment]
Sorry, I'm bothering you again.
I'm trying to use pywsd in my java application on netbeans. I didn't
succeed yet.
I appreciate, if you can help me on this issue too.

**Comment by alvations** [comment]
@SohaKh, integrating python library calls into netbeans won't be easy. I have personally not done that before but I've done the reverse of integrating java libraries into python and the easiest way was to stream in/output to command line (it's not recommended though).

I'm sorry that I can't help you on the java-python interface but maybe you'll find these helpful: http://stackoverflow.com/questions/1119696/java-python-integration or http://stackoverflow.com/questions/1075905/class-file-from-jython-with-pydev
