### ISSUE TITLE
Not compatible with Python 3?

### ISSUE THREAD

**Issue by coiby** [alvations/pywsd#26]
Hi,

It seems `pywsd` is not compatible with Python 3.

If I run `from pywsd.lesk import simple_lesk` in Python 3, the following error is given:

> Traceback (most recent call last):
>   File "wsd.py", line 28, in <module>
>     from pywsd.lesk import simple_lesk
>   File "/home/coiby/nlp/pywsd/pywsd/__init__.py", line 9, in <module>
>     import lesk
> ImportError: No module named 'lesk'

I manually add pywsd to `path` (`sys.path.append(os.path.join(os.path.dirname(__file__), 'pywsd'))`), another issue occurs:

> Traceback (most recent call last):
>   File "wsd.py", line 50, in <module>
>     answer = simple_lesk(sent, ambiguous)
>   File "/home/coiby/nlp/pywsd/pywsd/lesk.py", line 151, in simple_lesk
>     context_sentence = lemmatize_sentence(context_sentence)
>   File "pywsd/utils.py", line 104, in lemmatize_sentence
>     for word, pos in postagger(tokenizer(sentence)):
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/__init__.py", line 104, in word_tokenize
>     return [token for sent in sent_tokenize(text, language)
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/__init__.py", line 89, in sent_tokenize
>     return tokenizer.tokenize(text)
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 1226, in tokenize
>     return list(self.sentences_from_text(text, realign_boundaries))
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 1274, in sentences_from_text
>     return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 1265, in span_tokenize
>     return [(sl.start, sl.stop) for sl in slices]
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 1265, in <listcomp>
>     return [(sl.start, sl.stop) for sl in slices]
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 1304, in _realign_boundaries
>     for sl1, sl2 in _pair_iter(slices):
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 310, in _pair_iter
>     prev = next(it)
>   File "/usr/local/lib/python3.4/dist-packages/nltk/tokenize/punkt.py", line 1278, in _slices_from_text
>     for match in self._lang_vars.period_context_re().finditer(text):
> TypeError: can't use a string pattern on a bytes-like object

**Comment by alvations** [comment]
What is your input text, i.e. what is `sent` and `ambiguous` in `simple_lesk(sent, ambiguous)`? Which version of NLTK have you installed?

**Comment by coiby** [comment]
Thank you for the fast reply!

I re-check the code and found the second issue was my bad. To avoid a problem before, `ambiguous.encode('ascii', 'ignore')` was used. And NLTK3 doesn't support bytes-like object anymore so an error was thrown.

**Comment by alvations** [comment]
No problem.
