### ISSUE TITLE
similarity_by_infocontent is not working

### ISSUE THREAD

**Issue by tastyminerals** [alvations/pywsd#33]
Since you explicitly use `nltk.wordnet` calls I have no idea why you code does not work, but here you go:
```python
from pywsd.similarity import similarity_by_infocontent as sim
sim(syn,syn1,'res')
0
```
```python
from nltk.corpus import wordnet as wn
from nltk.corpus import wordnet_ic as wic
resnik = wic.ic('ic-bnc-resnik.dat')
wn.res_similarity(syn,syn1,resnik)
1.5972986298343528
```
Unfortunately that's true not only for "Resnik" but for any other sim method.

**Comment by alvations** [comment]
Which synsets are you comparing? 

Also, note that the code is using the `*-add1.dat`, instead of the normal `.dat` file.

**Comment by tastyminerals** [comment]
The synsets are identical in both cases otherwise my comment would make no sense :)

**Comment by tastyminerals** [comment]
```ipython
In [1]: from nltk.corpus import wordnet as wn
   ...: from nltk.corpus import wordnet_ic as wic
   ...: 
In [2]: from pywsd.similarity import similarity_by_infocontent as sim
In [3]: 
In [3]: s1 = wn.synsets('dog')[0]
In [4]: s2 = wn.synsets('wolf')[0]
In [5]: resnik = wic.ic('ic-bnc-resnik-add1.dat')
In [6]: sim(s1,s2,'res')
Out[6]: 0
In [7]: wn.res_similarity(s1,s2,resnik)
Out[7]: 8.510781257928674
```

**Comment by alvations** [comment]
The new overhaul `pywsd>=1.2.0` has a new wordnet info content interface. That should resolve this but yes more documentation is needed for this library. 

Closing the issue for now but if something comes up again, do reopen it.
