### ISSUE TITLE
disambiguate bug

### ISSUE THREAD

**Issue by AvivYaish** [alvations/pywsd#34]
Hi,
the function disambiguate seems to throw an exception when used like this:
`disambiguate(' letters oed much co')`

The exception is:

> Traceback (most recent call last):
>   File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-80-b3b0a70b5b6a>", line 1, in <module>
>     disambiguate(' letters oed much co')
>   File "C:\Program Files\Anaconda3\lib\site-packages\pywsd\allwords_wsd.py", line 35, in disambiguate
>     surface_words, lemmas, morphy_poss = lemmatize_sentence(sentence, keepWordPOS=True)
>   File "C:\Program Files\Anaconda3\lib\site-packages\pywsd\utils.py", line 107, in lemmatize_sentence
>     lemmatizer, stemmer))
>   File "C:\Program Files\Anaconda3\lib\site-packages\pywsd\utils.py", line 79, in lemmatize
>     stem = stemmer.stem(ambiguous_word)
>   File "C:\Program Files\Anaconda3\lib\site-packages\nltk\stem\porter.py", line 665, in stem
>     stem = self._step1b(stem)
>   File "C:\Program Files\Anaconda3\lib\site-packages\nltk\stem\porter.py", line 376, in _step1b
>     lambda stem: (self._measure(stem) == 1 and
>   File "C:\Program Files\Anaconda3\lib\site-packages\nltk\stem\porter.py", line 258, in _apply_rule_list
>     if suffix == '*d' and self._ends_double_consonant(word):
>   File "C:\Program Files\Anaconda3\lib\site-packages\nltk\stem\porter.py", line 214, in _ends_double_consonant
>     word[-1] == word[-2] and
> IndexError: string index out of range
>

**Comment by alvations** [comment]
This should work with the latest version of `pywsd==1.1.1`

```
>>> from pywsd import disambiguate
>>> disambiguate(' letters oed much co')
[('letters', Synset('letter.n.05')), ('oed', None), ('much', Synset('much.a.01')), ('co', Synset('conscientious_objector.n.01'))]
```

Do a `pip` upgrade:

```
pip3 install -U pywsd
```
