### ISSUE TITLE
typo in bibtex citation  

### ISSUE THREAD

**Issue by tastyminerals** [alvations/pywsd#36]
Even though it compiles I think there is a superfluous curly bracke in your pywsd citation.
The below version works only with `\usepackage[square,sort,comma,numbers]{natbib}` (but it turns all your citations into [digit] format which looks really bad)

```
@misc{pywsd14,
author =   {Liling Tan},
title =    {Pywsd: Python Implementations of Word Sense Disambiguation (WSD) Technologies [software]},
howpublished = {https://github.com/alvations/pywsd}},
year = {2014}
} 
```

Also, an alternative version that does not break the compilation in case `\usepackage{natbib}` used.

```
@misc{pywsd14,
    author = {Liling Tan},
    title = {{Pywsd: Python Implementations of Word Sense Disambiguation (WSD) Technologies [software]}},
    howpublished = "\url{https://github.com/alvations/pywsd}",
    year = {2014},
    note = "[Online; accessed 17-July-2016]"
}
```

**Comment by alvations** [comment]
Thanks @tastyminerals for spotting that! Removed it =)
