### ISSUE TITLE
Errors in similarity.py

### ISSUE THREAD

**Issue by AkhilRam7** [alvations/pywsd#41]
`def similarity_by_path(sense1, sense2, option="path"): 

    """ Returns maximum path similarity between two senses. """
    if option.lower() in ["path", "path_similarity"]: # Path similaritys
        return max(wn.path_similarity(sense1,sense2),
                   wn.path_similarity(sense1,sense2))`

Error in max(wn.path_similarity(sense1,sense2), wn.path_similarity(sense1,sense2))
finding max between same functions

**Comment by alvations** [comment]
@AkhilRam7 I'll need a little more details to understand what is the issue and how to resolve it:

- How did you call the function?
- What is the input that you have used for to get an error? 
- What is the error in trackback?

**Comment by AkhilRam7** [comment]
Replacing  `return max(wn.path_similarity(sense1,sense2), wn.path_similarity(sense1,sense2))` with 
`return wn.path_similarity(sense1,sense2`  solved the error

**Comment by alvations** [comment]
@AkhilRam7 that  doesn't exactly help in understanding what caused the problem and know how to solve the error. Could you to answer the questions below so that I could find out how to resolve the issue?

- How did you call the function?
- What is the input that you have used for to get an error?
- What is the error in trackback?

**Comment by AkhilRam7** [comment]
**for j in context_sentence) TypeError: '>' not supported between instances of 'NoneType' and 'float'**
This is the error in terminal when i used max_similarity function.

For few words path_similarity returns **None** .

**Comment by alvations** [comment]
Fixed in the new overhaul =)

Thanks @AkhilRam7 @cyrilou242!
