### ISSUE TITLE
Using wup_similarity on simple_lesk output

### ISSUE THREAD

**Issue by PhilWicke** [alvations/pywsd#54]
First of all, thank you for this library. I've been using your simple_lesk implementation for a project. But now, after I've installed the latest version of your lib on a different machine, I fail to be able to call the wup_similarity on the object returned by the simple_lesk function.

`example = simple_lesk("This is an example", "example")`
`example.wup_similarity(example)`
`>>>Traceback (most recent call last):`
`>>>  File "<input>", line 1, in <module>`
`>>>AttributeError: 'Synset' object has no attribute 'wup_similarity'`

In a previous implementation I have been able to do that. I just wanted to understand whether this is my system causing the issue or if there is a fix to that.

Thank you for your time.

**Comment by PhilWicke** [comment]
You can close this. Using the fix:

`wn.synset(example.name()).wup_similarity(wn.synset(example.name()))`

**Comment by alvations** [comment]
@PhilWicke Yes, we are using this https://github.com/alvations/wordnet version of the wordnet reader to speed things up now and it's a little different from the NLTK version.
