### ISSUE TITLE
Notice: please pin wn dependency

### ISSUE THREAD

**Issue by goodmami** [alvations/pywsd#62]
I'm preparing to release wn 0.1.0 on PyPI and, for the most part, it will not be compatible with the current release (0.0.23). The requirements.txt file in this repository says `wn>=0.0.19`, meaning it will pull a later version if one is available. I suggest pinning this to `wn==0.0.23` so things won't break. When the new release has reached feature parity with the old one (in particular, see https://github.com/goodmami/wn/issues/40), then perhaps it could be updated to use the new module.

**Comment by gavishpoddar** [comment]
+1

**Comment by goodmami** [comment]
@alvations it looks like this might be starting to affect people. I created a PR which pins the dependency in `requirements.txt` and `setup.py`.
